feat(whisper-stream): add support for environment variables for OpenAI API URLs and token feat(whisper-stream): update model to "whisper-large-v3-turbo" for improved transcription accuracy feat(whisper-stream): add DEST_FILE option to specify output file for transcriptions feat(whisper-stream): add support for xsel clipboard utility to copy transcriptions to clipboard feat(whisper-stream): add support for writing transcriptions to a specified destination file feat(whisper-stream): add support for selecting a notebook directory for storing transcriptions feat(whisper-stream): update audio recording settings to use 16-bit, 1-channel, 16kHz audio format for improved compatibility and performance

diff --git a/whisper-stream b/whisper-stream
--- a/whisper-stream
+++ b/whisper-stream
@@ -8,9 +8,12 @@ MIN_VOLUME=1%                  # Minimum volume threshold
 SILENCE_LENGTH=1.5             # Minimum silence duration in seconds
 ONESHOT=false                  # Flag to determine if the script should run once or continuously
 DURATION=0                     # Duration of the recording in seconds (0 means continuous)
-MODEL="whisper-1"              # Model for the OpenAI API
-TOKEN=""                       # OpenAI API token
+WHISPER_URL_TRANSLATIONS="https://api.groq.com/openai/v1/audio/translations"
+WHISPER_URL_TRANSCRIPTIONS="https://api.groq.com/openai/v1/audio/transcriptions"
+MODEL="whisper-large-v3-turbo"              # Model for the OpenAI API
+TOKEN="${GROQ_API_KEY}"                       # OpenAI API token
 OUTPUT_DIR=""                  # Directory to save the transcriptions
+DEST_FILE=""       # File to write the transcriptions to
 PROMPT=""                      # Prompt for the API call
 LANGUAGE=""                    # Language code for transcription
 TRANSLATE=""                   # Flag to indicate translation to English
@@ -146,6 +149,22 @@ while [[ $# -gt 0 ]]; do
       shift
       shift
       ;;
+    -e | --dictation)
+      if [[ ! $2 || $2 == -* ]]; then
+        echo "Error: Missing value for $1"
+        exit 1
+      fi
+      DEST_FILE="$2"
+
+      # OUTPUT_DIR="$HOME/Workspace/Notebook/_transcriptions"
+      # check if the file exists
+      if [ ! -f "$DEST_FILE" ]; then
+        echo "File does not exist: $DEST_FILE"
+        exit 1
+      fi
+      shift
+      shift
+      ;;      
     -g|--granularities)
       if [[ ! $2 || $2 == -* ]]; then
         echo "Error: Missing value for $1"
@@ -290,6 +309,10 @@ function display_settings() {
     echo "  Output Dir: $OUTPUT_DIR"
   fi
 
+	if [ -n "$DEST_FILE" ]; then
+		echo "  Destination File: $DEST_FILE"
+	fi
+
   # Get the input device based on the operating system
   local input_device=$(get_input_device)
   if [ -n "$input_device" ]; then
@@ -355,16 +378,17 @@ function spinner() {
 function convert_audio_to_text() {
   local output_file=$1
   if [ -n "$TRANSLATE" ]; then
-    base_url="https://api.openai.com/v1/audio/translations"
+    base_url="$WHISPER_URL_TRANSLATIONS"
   else
-    base_url="https://api.openai.com/v1/audio/transcriptions"
+    base_url="$WHISPER_URL_TRANSCRIPTIONS"
   fi
   local curl_command="curl -s --request POST \
     --url $base_url \
-    --header \"Authorization: Bearer $TOKEN\" \
+    --header \"Authorization: Bearer ${TOKEN}\" \
     --header \"Content-Type: multipart/form-data\" \
     --form \"file=@$output_file\" \
     --form \"model=$MODEL\" \
+    --form \"temperature=0.02\" \
     --form \"response_format=verbose_json\""
 
   # Add optional parameters to the curl command when GANULARITIES is not set to none
@@ -396,7 +420,7 @@ function convert_audio_to_text() {
   if [ "$GRANULARITIES" != "none" ]; then
     transcription=$(echo "$response")
   else
-    transcription=$(echo "$response" | jq -r '.text')
+    transcription=$(echo "$response" | jq -r '.text' | sd '^\s' '')
   fi
   
   # Check if the curl command was successful
@@ -409,7 +433,16 @@ function convert_audio_to_text() {
   done
 
   printf "\r\e[K"
+	xsel -cb
+	xsel -a -b <<<$transcription  
   echo "$transcription"
+
+	if [ -n "${DEST_FILE}" ]; then
+		# Write the transcription to the destination file
+		# LLMEDIT=$(aichat -r transcription_editor 'NLP' "${transcription}")
+		echo "$transcription" >> "${DEST_FILE}"
+		# echo "$LLMEDIT" >> "${DEST_FILE}"
+	fi
 
   if [ -n "$PIPE_TO_CMD" ]; then
     result=$(echo "$transcription" | $PIPE_TO_CMD)
@@ -530,10 +563,21 @@ display_settings
 # Handle script termination using trap for SIGINT (Ctrl+C) and SIGTSTP (Ctrl+Z)
 trap handle_exit SIGINT SIGTSTP
 
+echo "Choose a notebook:"
+notebook=$(gum file --height=10 --directory "$HOME/Desktop" --file=false)
+if [ ! -d "$notebook" ]; then
+  echo "Error: Selected notebook directory does not exist."
+  exit 1
+fi
+dictations="${notebook}/_dictations"
+mkdir -p "$dictations"
+
+export AUDIODRIVER=alsa
+
 # Main loop to continuously record audio, detect silence, and transcribe audio
 while true; do
   # Set the path to the output audio file
-  OUTPUT_FILE="output_$(date +%s).mp3"
+  OUTPUT_FILE="output_$(date +%s).wav"
   
   # Add the output file to the array
   output_files+=("$OUTPUT_FILE")
@@ -543,13 +587,13 @@ while true; do
 
   # Record audio in raw format then convert to mp3
   if [ "$DURATION" -gt 0 ]; then
-    rec -q -V0 -e signed -L -c 1 -b 16 -r 44100 -t raw \
+    rec -q -V0 -e signed -L -c 1 -b 16 -r 16000 -t raw \
       - trim 0 "$DURATION" silence 1 0.1 "$MIN_VOLUME" 1 "$SILENCE_LENGTH" "$MIN_VOLUME" | \
-      sox -t raw -r 44100 -b 16 -e signed -c 1 - "$OUTPUT_FILE"
+      sox -t raw -r 16000 -b 16 -e signed -c 1 - "$OUTPUT_FILE"
   else
-    rec -q -V0 -e signed -L -c 1 -b 16 -r 44100 -t raw \
+    rec -q -V0 -e signed -L -c 1 -b 16 -r 16000 -t raw \
       - silence 1 0.1 "$MIN_VOLUME" 1 "$SILENCE_LENGTH" "$MIN_VOLUME" | \
-      sox -t raw -r 44100 -b 16 -e signed -c 1 - "$OUTPUT_FILE"
+      sox -t raw -r 16000 -b 16 -e signed -c 1 - "$OUTPUT_FILE"
   fi
   
   # Check if the audio file is created successfully
